name: Daily Firestore to BigQuery Ingestion

on:
  schedule:
    # Tourne tous les jours à 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Bouton pour lancer manuellement dans l'onglet Actions

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Installation des dépendances nécessaires pour Python
      - name: Install dependencies
        run: |
          pip install google-cloud-firestore google-cloud-bigquery pandas db-dtypes

      # Exécution du script avec la clé secrète récupérée dans les Secrets GitHub
      - name: Run Ingestion Script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: python ingestion.py
